import './global.css';
import { Container, Navbar } from '@apus/ui';
import { Manrope } from 'next/font/google'

export const metadata = {
  title: 'Welcome to schools',
  description: 'Generated by create-nx-workspace',
};

const manrope = Manrope({ subsets: ['latin'] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={manrope.className}>
          <Navbar title='Teste Técnico - Lucas Toledo Pereira' logo='/images/logos/apus.png'/>
          <Container>{children}</Container>
      </body>
    </html>
  );
}
