import './global.css';
import { Container, Navbar } from '@apus/ui';

export const metadata = {
  title: 'Welcome to schools',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
          <Navbar title='Teste Técnico - Lucas Toledo Pereira' logo='/images/logos/apus.png'/>
          <Container>{children}</Container>
      </body>
    </html>
  );
}
